---
- name: Deploy React App
  hosts: localhost
  connection: local

  tasks:
    - name: Deploy to Docker Swarm
      docker_stack:
        name: "react"
        state: present
        compose:
          - version: "3.7"
            services:
              react:
                image: react:latest
                ports:
                  - "5000:8080"
        resolve_image: always
